app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/


Route::controller('auth', 'Auth\AuthController');
Route::get('pw/{token}', ['as' => 'password/token', 'uses' => 'Auth\PasswordController@getReset']);
Route::post('password', ['as' => 'password/reset', 'uses' => 'Auth\PasswordController@postReset']);


Route::group(['middleware' => ['auth']], function() {
    //Route::controller('users', 'UsersController');
    Route::get('anketa/{id}/fmsExcel', ['uses' => 'UsersController@fms']);
    Route::get('/', ['uses' => 'HomeController@index']);

    Route::group(['middleware' => ['ability:admin,']], function() {


        Route::group(['prefix' => 'po', 'namespace' => 'PO'], function() {
            Route::resource('objects', 'ObjectController');
            Route::get('objects/{id}/delete', [
                'as' => 'po.objects.delete',
                'uses' => 'ObjectController@destroy',
            ]);
            Route::group(['prefix' => 'object/{object}'], function() {
                Route::get('expense', ['as' => 'po.expense.index', 'uses' => 'ExpenseController@index']);
                Route::post('expense', ['as' => 'po.expense.update', 'uses' => 'ExpenseController@postIndex']);

                Route::get('applications', ['as' => 'po.applications.index','uses' => 'ApplicationController@index']);
                Route::get('applications/create', ['as' => 'po.applications.create','uses' => 'ApplicationController@create']);
                Route::post('applications/create', ['as' => 'po.applications.store','uses' => 'ApplicationController@store']);
                Route::get('applications/{id}/edit', ['as' => 'po.applications.edit','uses' => 'ApplicationController@edit']);
                Route::patch('applications/{id}/update', ['as' => 'po.applications.update','uses' => 'ApplicationController@update']);
                Route::get('applications/{id}/delete', ['as' => 'po.applications.delete','uses' => 'ApplicationController@destroy']);
            });
            Route::get('expenses', ['as' => 'po.expense.all.index', 'uses' => 'ExpenseController@all']);
            Route::get('applications', ['as' => 'po.applications.all.index','uses' => 'ApplicationController@all']);


            /*
            |--------------------------------------------------------------------------
            | Вакансии
            |--------------------------------------------------------------------------
            */
            Route::resource('vacancies', 'VacancyController');
            Route::get('vacancies/{id}/delete', [
                'as' => 'po.vacancies.delete',
                'uses' => 'VacancyController@destroy',
            ]);

            Route::resource('passportOffices', 'PassportOfficesController');

        });


        /*--------------------------------
        Cлужба Безопасности
        --------------------------------*/
        Route::resource('sbUsers', 'SbUsersController');
        Route::get('sbUsers/{id}/delete', ['as' => 'sbUsers.delete','uses' => 'SbUsersController@destroy']);

        Route::group(['prefix' => 'sb'], function() {
            Route::get('users', ['as' => 'sb.users', 'uses' => 'SbUsersController@index']);
        });

        Route::group(['prefix' => 'admin'], function() {
            Route::group(['prefix' => 'users'], function() {
                Route::match(['get','post'], '', ['as' => 'admin.users.index', 'uses' => 'AdminController@user']);
                Route::get('create', ['as' => 'admin.users.create', 'uses' => 'AdminController@userCreate']);
                Route::post('store', ['as' => 'admin.users.store', 'uses' => 'AdminController@userStore']);
                Route::get('{id}/delete', ['as' => 'admin.users.delete', 'uses' => 'AdminController@userDestroy']);
                Route::get('{id}/edit', ['as' => 'admin.users.edit', 'uses' => 'AdminController@userEdit']);
                Route::patch('{id}/update', ['as' => 'admin.users.update', 'uses' => 'AdminController@userUpdate']);

                Route::group(['prefix' => 'logs'], function() {
                    Route::match(['get','post'], 'auth', ['as' => 'admin.users.log', 'uses' => 'LoginLogController@report']);
                });
            });

            Route::get('applicationLogs', ['as' => 'admin.applicationLogs', 'uses' => '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index' ]);

            Route::group(['prefix' => 'roles'], function() {
                Route::get('', ['as' => 'admin.roles.index', 'uses' => 'AdminController@roles']);
                Route::get('create', ['as' => 'admin.roles.create', 'uses' => 'AdminController@rolesCreate']);
                Route::post('store', ['as' => 'admin.roles.store', 'uses' => 'AdminController@rolesStore']);
                Route::get('{id}/edit', ['as' => 'admin.roles.edit', 'uses' => 'AdminController@rolesEdit']);
                Route::patch('{id}/update', ['as' => 'admin.roles.update', 'uses' => 'AdminController@rolesUpdate']);
            });
        });
    });

    Route::group(['middleware' => ['ability:admin,employment-agencies']], function() {
        Route::resource('agencyStaffing', 'AgencyStaffingController');
        Route::get('agencyStaffing/{id}/delete', ['as' => 'agencyStaffing.delete','uses' => 'AgencyStaffingController@destroy']);

        Route::resource('agencyContacts', 'AgencyContactController');
        Route::get('agencyContacts/{id}/delete', ['as' => 'agencyContacts.delete', 'uses' => 'AgencyContactController@destroy']);
    });

    Route::group(['prefix' => 'scheduler'], function() {
        Route::get('', ['uses' => 'SchedulerController@index', 'middleware' => 'ability:admin,']);
        Route::post('ajax', ['uses' => 'SchedulerController@ajax']);
        Route::post('ajaxuploadfile', ['uses' => 'SchedulerController@ajaxuploadfile']);
        Route::post('ajaxdeletefile', ['uses' => 'SchedulerController@ajaxdeletefile']);
        Route::get('mytasks', ['uses' => 'SchedulerController@mytasks']);
        Route::post('mytasks', ['uses' => 'SchedulerController@mytasks']);
        Route::get('mytasks/show/{task_i?}', ['uses' => 'SchedulerController@showtasks']);
        Route::post('mytasks/show/{task_i?}', ['uses' => 'SchedulerController@showtasks']);
        Route::get('mytasks/showakt/{akt_i?}', ['uses' => 'SchedulerController@showakt']);
        Route::post('ajaxact', ['uses' => 'SchedulerController@ajaxact']);
    });

    Route::group(['prefix' => 'support', 'namespace' => 'Support'], function() {
        Route::get('addtiket', ['uses' => 'SupportController@addtiket']);
        Route::post('ajax', ['uses' => 'SupportController@ajax']);
        Route::post('ajaxform', ['uses' => 'SupportController@ajaxform']);

        Route::get('stattiket', ['uses' => 'SupportController@stattiket', 'middleware' => 'ability:admin,']);
        Route::group(['middleware' => 'ability:admin,support-manager'], function() {
            Route::get('listtiket', ['as' => 'support.listtiket', 'uses' => 'SupportController@listtiket']);
            Route::get('viewtiket', ['as' => 'support.viewtiket', 'uses' => 'SupportController@viewtiket']);
            Route::post('addjiro', ['uses' => 'SupportController@addjiro']);
            Route::get('formcomplite', ['uses' => 'SupportController@formcomplite']);
        });

        Route::post('chkauth', ['uses' => 'SupportController@chkauth']);

        Route::get('maintikets', ['uses' => 'SupportController@maintikets']);
        Route::post('maintikets', ['uses' => 'SupportController@maintikets']);
    });

    /*--------------------------------
    Отчет Fullbase
    --------------------------------*/
    Route::group(['middleware' => ['ability:admin,employment-requests']],function() {
        Route::match(['get','post'], '/fullbase', ['uses' => 'FullbaseController@index']);
        Route::get('/edit/create', ['uses' => 'EditController@create']);
        Route::get('/edit/update/{id?}', ['uses' => 'EditController@update']);
        Route::post('/edit/sms_send_addr', ['uses' => 'EditController@ajaxsms']);
        Route::post('/edit/getphones', ['uses' => 'EditController@getphones']);
        Route::post('/edit/formupdate', ['uses' => 'EditController@formupdate']);
        Route::get('/edit/ajax', ['uses' => 'EditController@ajax']);
        Route::post('/edit/ajax', ['uses' => 'EditController@ajax']);
        Route::post('/fullbase/feelds', ['uses' => 'FullbaseController@setFeeldsSoiskateli']);
    });

    /*------------------------
    Банковские карты
    ------------------------*/
    Route::group(['middleware' => ['ability:admin,bank-card']], function() {
        Route::group(['prefix' => 'bankcard',], function () {
            Route::get('', ['as' => 'bankcard.index', 'uses' => 'BankcardController@index']);
            Route::post('ajax', ['uses' => 'BankcardController@ajax']);
            Route::post('', ['uses' => 'BankcardController@index']);
        });
    });
    /*--------------------------------
    Контрагенты
    --------------------------------*/
    Route::group(['prefix' => 'contractor', 'middleware' => ['ability:admin,contractor']], function() {
        Route::match(['get', 'post'],'', ['as' => 'contractor.index', 'uses' => 'ContractorController@index']);
        Route::get('create', ['as' => 'contractor.create', 'uses' => 'ContractorController@create']);
        Route::post('store', ['as' => 'contractor.store', 'uses' => 'ContractorController@store']);
        Route::get('{id}/edit', ['as' => 'contractor.edit', 'uses' => 'ContractorController@edit']);

app/Models/PersMain.php
<?php namespace App\Models;

use Illuminate\Database\Eloquent\Model as Model;

class PersMain extends Model
{
	public function passport()
	{
		return $this->hasOne('App\Models\PersPassport', 'id_anketa', 'id_anketa');
	}
	public function status()
	{
		return $this->hasOne('App\Models\PersStatus', 'id_anketa', 'id_anketa');
	}
	public function dormitory()
	{
		return $this->belongsTo('App\Models\DirDormitoryFms', 'dormitory_fms_id');
	}

	public function advance()
	{
		return $this->hasMany('App\Models\TuovAdvance', 'id_anketa', 'anketa_id');
	}
    
	public $table = "pers_main";

	protected $primaryKey = 'id_anketa';

	public $timestamps = false;

	public $fillable = [
	    "id_anketa",
		"old_id",
		"create_date",
		"dog_num",
		"meet_date",
		"firstname",
		"lastname",
		"patronymic",
		"nation",
		"birth_date",
		"birth_place",
		"age",
		"gender",
		"family_status",
		"education",
		"speciality",
		"find_with",
		"subdivision",
		"criminal",
		"to_army",
		"in_army",
		"pmo",
		"criminal_state",
		"criminal_status",
		"medical_type",
		"medical_status",
		"medical_expire",
		"disabled",
		"disable_date",
		"badge_number",
		"no_money",
		"no_sim"
	];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        "id_anketa" => "integer",
		"old_id" => "integer",
		"dog_num" => "string",
		"firstname" => "string",
		"lastname" => "string",
		"patronymic" => "string",
		"nation" => "string",
		"birth_place" => "string",
		"age" => "boolean",
		"gender" => "boolean",
		"family_status" => "boolean",
		"education" => "boolean",
		"speciality" => "string",
		"find_with" => "string",
		"subdivision" => "string",
		"criminal" => "boolean",
		"to_army" => "boolean",
		"in_army" => "boolean",
		"pmo" => "string",
		"criminal_state" => "string",
		"criminal_status" => "boolean",
		"medical_type" => "boolean",
		"medical_status" => "boolean",
		"disabled" => "boolean",
		"badge_number" => "integer",
		"no_money" => "boolean",
		"no_sim" => "boolean"
    ];

	public static $rules = [
	    
	];

	/**
	 * Анкета белоруса имеющего статус "Принят"
	 * @param $query
	 * @return mixed
	 */
	public function scopeBelarusAccepted($query)
	{
		return $query->whereNation(2)->whereHas('status', function($q) {
			$q->where('status_name', 9);
		});
	}

	public function saveDormitory() {
		$this->dormitory()->associate(DirDormitoryFms::all()->random(1))->save();
	}

	public function getFioAttribute() {
		return sprintf('%s %s %s', $this->lastname, $this->firstname, $this->patronymic);
	}
}

resources/views/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ $app_title or 'Laravel' }} - {{ Config('app.url')}}</title>

    <link href="{{ asset('/css/app.css') }}" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{{ URL::asset('/bootstrap/css/bootstrap.min.css') }}"/>
    <link rel="stylesheet" type="text/css" href="{{ URL::asset('/js/libs/select2/select2.css') }}"/>

    <!-- Fonts -->
    <link href='//fonts.googleapis.com/css?family=Roboto:400,300' rel='stylesheet' type='text/css'>
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>

    <![endif]-->
    <meta name="csrf-token" content="{{ csrf_token() }}"/>
    <script>
        @if( Auth::check() )
        var mylogin = "{{ Auth()->user()->username }}";
        var myip = "{{ Request::ip() }}";
        @endif
    </script>

    @yield('head')

    {!! Html::script('//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js') !!}
    {!! Html::script('/js/jquery-ui/jquery.ui.datepicker-ru.js') !!}
    {!! Html::script('/js/libs/select2/select2.min.js') !!}
    {!! Html::script('/js/libs/select2/i18n/ru.js') !!}
    {!! Html::script('/js/socket-io/socket.io-1.3.7.js') !!}
    {!! Html::script('/bootstrap/js/bootstrap.min.js') !!}
    {!! Html::script('/js/core.js') !!}

    @if ( App::environment('production') )
        {!! Html::script('/js/asterisk/aster-client.js') !!}
    @endif


</head>
<body>
@yield('nav')

@yield('content')

    <!-- Scripts -->
@yield('scripts')

@if ( App::environment('production') )
    @yield('bottomnav')
@endif
</body>
</html>

resources/views/home.blade.php
@extends('app')

@extends('nav')

@section('content')
<div class="container">
	<div class="row">
		<div class="col-md-10 col-md-offset-1">
			<div class="panel panel-default">
				<div class="panel-heading">Home</div>

				<div class="panel-body">
					Добрый день, {{ Auth()->user()->fio }}!
					<br><br>
					<a href="/auth/logout" class="btn btn-default">
						<span class="glyphicon glyphicon-log-out" aria-hidden="true"></span>
						Выйти
					</a>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/nav.blade.php
@section('nav')
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle Navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <!--	<a class="navbar-brand" href="#">Laravel</a> -->
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            {!! $menu !!}

            <ul class="nav navbar-nav navbar-right">
                @if (Auth::user())
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">{{ Auth::user()->username}} <span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="{{ url('/lcab/telegrams') }}">Телеграм</a></li>
                            <li><a href="{{ url('/personal_area') }}">Личный кабинет</a></li>
                            <li><a href="{{ url('/auth/logout') }}"><span class="glyphicon glyphicon-log-out" aria-hidden="true"></span> Выйти</a></li>
                        </ul>
                    </li>
                @endif
            </ul>
        </div>

    </div>
</nav>
@endsection

@section('bottomnav')
    <div style="height: 51px;"></div>
    <nav class="navbar navbar-inverse navbar-fixed-bottom">
        <div id="bottom-brand" class="navbar-header">
        </div>
        <div id="calls" class="container">
            <ul class="nav navbar-nav">
                <li class="active" role="presentation"><a href="/edit/create" target="_blank">Новая заявка</a></li>
            </ul>
        </div>
    </nav>
@endsection

resources/views/register.blade.php
@extends('app')

@section('content')
<style>
.req_field {
color:red;
margin-left:3px;
}
</style>
<div class="container-fluid">
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<div class="panel panel-default">
				<div class="panel-heading">{{isset($user->id)?'Изменение данных пользователя':'Добавление пользователя'}}</div>
				<div class="panel-body">
					@if (count($errors) > 0)
						<div class="alert alert-danger">
							<strong>Ошибка!</strong> Возникли проблемы с заполнением формы регистрации.<br><br>
							<ul>
								@foreach ($errors as $error)
									<li>{{ $error }}</li>
								@endforeach
							</ul>
						</div>
					@endif

					<form class="form-horizontal" role="form" method="POST"">
						<input type="hidden" name="_token" value="{{ csrf_token() }}">

						<div class="form-group">
							<label class="col-md-4 control-label">Логин <span class="req_field">*</span></label>
							<div class="col-md-6">
								<input type="text" class="form-control" name="username" value="{{ isset($user) ? $user->username : old('username') }}">
							</div>
						</div>
						
						<div class="form-group">
							<label class="col-md-4 control-label">ФИО <span class="req_field">*</span></label>
							<div class="col-md-6">
								<input type="text" class="form-control" name="fio" value="{{ isset($user) ? $user->fio : old('fio') }}">
							</div>
						</div>
						
						<div class="form-group">
							<label class="col-md-4 control-label">Телефон</label>
							<div class="col-md-6">
								<input type="text" class="form-control" name="phone" value="{{ isset($user) ? $user->phone : old('phone') }}">
							</div>
						</div>
						
						<div class="form-group">
							<label class="col-md-4 control-label">Внутренний номер</label>
							<div class="col-md-6">
								<input type="text" class="form-control" name="myextension" value="{{ isset($user) ? $user->myextension : old('myextension') }}">
							</div>
						</div>

						<div class="form-group">
							<label class="col-md-4 control-label">E-Mail</label>
							<div class="col-md-6">
								<input type="email" class="form-control" name="email" value="{{ isset($user) ? $user->email : old('email') }}">
							</div>
						</div>
						
						<div class="form-group">
							<label class="col-md-4 control-label">Активен</label>
							<div class="col-md-6">
								<select class="form-control" name="enable">
									@foreach ($lists['enable'] as $k=>$val)
										<option value="{{$k}}" {{(isset($user) && $user->enable==$k) ? 'selected' :''}}>{{$val}}</option>
									@endforeach
								</select>								
								</select>
							</div>
						</div>
						
						<div class="form-group">
							<label class="col-md-4 control-label">Статус</label>
							<div class="col-md-6">
								<select class="form-control" name="status">
									@foreach ($lists['users_status'] as $k=>$val)
										<option value="{{$k}}" {{(isset($user) && $user->status==$k) ? 'selected' :''}}>{{$val}}</option>
									@endforeach
								</select>
							</div>
						</div>
						
						
						<div class="form-group">
							<label class="col-md-4 control-label">Пароль @if (!isset($user->id))<span class="req_field">*</span>@endif</label>
							<div class="col-md-6">
								<input type="password" class="form-control" name="password"  @if (isset($user->id)) placeholder="Оставьте пустым, если не хотите менять пароль" @endif >
							</div>
						</div>

						<div class="form-group">
							<label class="col-md-4 control-label">Подтверждение пароля @if (!isset($user->id))<span class="req_field">*</span>@endif</label>
							<div class="col-md-6">
								<input type="password" class="form-control" name="password_confirmation">
							</div>
						</div>

						<div class="form-group">
							<div class="col-md-6 col-md-offset-4">
								<button type="submit" class="btn btn-primary">
									Сохранить
								</button>
							</div>
						</div>
						<input type="hidden" name="id" value="{{ isset($user->id) ? $user->id:''}}">
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/users.blade.php
@extends('app')

@section('content')
<style>
#users_table  {
margin-top:10px;
}

#users_table td,th{
padding:7px;
}
#users_table th {
text-align:center;
}
</style>
<div class="container">
	<div class="row">
		<div class="col-md-10 col-md-offset-1">
			<div class="panel panel-default">
				<div class="panel-heading">Пользователи</div>
				
				<div class="panel-body">
				<a href="/users/add-form">Добавить пользователя</a>
					<table border="1" id="users_table">
						<tr>
							<th>ID</th>
							<th>Фио</th>
							<th>Логин</th>
							<th>Статус</th>
							<th>Активность</th>
							<th>Авторизация</th>
							<th>Последнее действие</th>
							<th colspan="2">Действия</th>
						
						</tr>
						@foreach ($users as $user)
						<tr>
							<td>{{$user->userid}}</td>
							<td>{{$user->fio}}</td>
							<td>{{$user->username}}</td>
							<td align="center">{{$lists['users_status'][$user->status]}}</td>
							<td align="center">{{$lists['enable'][$user->enable]}}</td>
							<td>{{$user->login_date}}</td>
							<td>{{$user->last_date}}</td>
							<td><a href="/users/update-form/{{$user->userid}}">Изменить</a></td>
							<td><a href="/users/delete/{{$user->userid}}" onclick="return confirm('Вы уверены?');">Удалить</a></td>
						</tr>
						@endforeach
				</div>
			</div>
		</div>
	</div>
</div>
@endsection