app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/


Route::controller('auth', 'Auth\AuthController');
Route::get('pw/{token}', ['as' => 'password/token', 'uses' => 'Auth\PasswordController@getReset']);
Route::post('password', ['as' => 'password/reset', 'uses' => 'Auth\PasswordController@postReset']);


Route::group(['middleware' => ['auth']], function() {
    //Route::controller('users', 'UsersController');
    Route::get('anketa/{id}/fmsExcel', ['uses' => 'UsersController@fms']);
    Route::get('/', ['uses' => 'HomeController@index']);

    Route::group(['middleware' => ['ability:admin,']], function() {


        Route::group(['prefix' => 'po', 'namespace' => 'PO'], function() {
            Route::resource('objects', 'ObjectController');
            Route::get('objects/{id}/delete', [
                'as' => 'po.objects.delete',
                'uses' => 'ObjectController@destroy',
            ]);
            Route::group(['prefix' => 'object/{object}'], function() {
                Route::get('expense', ['as' => 'po.expense.index', 'uses' => 'ExpenseController@index']);
                Route::post('expense', ['as' => 'po.expense.update', 'uses' => 'ExpenseController@postIndex']);

                Route::get('applications', ['as' => 'po.applications.index','uses' => 'ApplicationController@index']);
                Route::get('applications/create', ['as' => 'po.applications.create','uses' => 'ApplicationController@create']);
                Route::post('applications/create', ['as' => 'po.applications.store','uses' => 'ApplicationController@store']);
                Route::get('applications/{id}/edit', ['as' => 'po.applications.edit','uses' => 'ApplicationController@edit']);
                Route::patch('applications/{id}/update', ['as' => 'po.applications.update','uses' => 'ApplicationController@update']);
                Route::get('applications/{id}/delete', ['as' => 'po.applications.delete','uses' => 'ApplicationController@destroy']);
            });
            Route::get('expenses', ['as' => 'po.expense.all.index', 'uses' => 'ExpenseController@all']);
            Route::get('applications', ['as' => 'po.applications.all.index','uses' => 'ApplicationController@all']);


            /*
            |--------------------------------------------------------------------------
            | Вакансии
            |--------------------------------------------------------------------------
            */
            Route::resource('vacancies', 'VacancyController');
            Route::get('vacancies/{id}/delete', [
                'as' => 'po.vacancies.delete',
                'uses' => 'VacancyController@destroy',
            ]);

            Route::resource('passportOffices', 'PassportOfficesController');

        });


        /*--------------------------------
        Cлужба Безопасности
        --------------------------------*/
        Route::resource('sbUsers', 'SbUsersController');
        Route::get('sbUsers/{id}/delete', ['as' => 'sbUsers.delete','uses' => 'SbUsersController@destroy']);

        Route::group(['prefix' => 'sb'], function() {
            Route::get('users', ['as' => 'sb.users', 'uses' => 'SbUsersController@index']);
        });

        Route::group(['prefix' => 'admin'], function() {
            Route::group(['prefix' => 'users'], function() {
                Route::match(['get','post'], '', ['as' => 'admin.users.index', 'uses' => 'AdminController@user']);
                Route::get('create', ['as' => 'admin.users.create', 'uses' => 'AdminController@userCreate']);
                Route::post('store', ['as' => 'admin.users.store', 'uses' => 'AdminController@userStore']);
                Route::get('{id}/delete', ['as' => 'admin.users.delete', 'uses' => 'AdminController@userDestroy']);
                Route::get('{id}/edit', ['as' => 'admin.users.edit', 'uses' => 'AdminController@userEdit']);
                Route::patch('{id}/update', ['as' => 'admin.users.update', 'uses' => 'AdminController@userUpdate']);

                Route::group(['prefix' => 'logs'], function() {
                    Route::match(['get','post'], 'auth', ['as' => 'admin.users.log', 'uses' => 'LoginLogController@report']);
                });
            });

            Route::get('applicationLogs', ['as' => 'admin.applicationLogs', 'uses' => '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index' ]);

            Route::group(['prefix' => 'roles'], function() {
                Route::get('', ['as' => 'admin.roles.index', 'uses' => 'AdminController@roles']);
                Route::get('create', ['as' => 'admin.roles.create', 'uses' => 'AdminController@rolesCreate']);
                Route::post('store', ['as' => 'admin.roles.store', 'uses' => 'AdminController@rolesStore']);
                Route::get('{id}/edit', ['as' => 'admin.roles.edit', 'uses' => 'AdminController@rolesEdit']);
                Route::patch('{id}/update', ['as' => 'admin.roles.update', 'uses' => 'AdminController@rolesUpdate']);
            });
        });
    });

    Route::group(['middleware' => ['ability:admin,employment-agencies']], function() {
        Route::resource('agencyStaffing', 'AgencyStaffingController');
        Route::get('agencyStaffing/{id}/delete', ['as' => 'agencyStaffing.delete','uses' => 'AgencyStaffingController@destroy']);

        Route::resource('agencyContacts', 'AgencyContactController');
        Route::get('agencyContacts/{id}/delete', ['as' => 'agencyContacts.delete', 'uses' => 'AgencyContactController@destroy']);
    });

    Route::group(['prefix' => 'scheduler'], function() {
        Route::get('', ['uses' => 'SchedulerController@index', 'middleware' => 'ability:admin,']);
        Route::post('ajax', ['uses' => 'SchedulerController@ajax']);
        Route::post('ajaxuploadfile', ['uses' => 'SchedulerController@ajaxuploadfile']);
        Route::post('ajaxdeletefile', ['uses' => 'SchedulerController@ajaxdeletefile']);
        Route::get('mytasks', ['uses' => 'SchedulerController@mytasks']);
        Route::post('mytasks', ['uses' => 'SchedulerController@mytasks']);
        Route::get('mytasks/show/{task_i?}', ['uses' => 'SchedulerController@showtasks']);
        Route::post('mytasks/show/{task_i?}', ['uses' => 'SchedulerController@showtasks']);
        Route::get('mytasks/showakt/{akt_i?}', ['uses' => 'SchedulerController@showakt']);
        Route::post('ajaxact', ['uses' => 'SchedulerController@ajaxact']);
    });

    Route::group(['prefix' => 'support', 'namespace' => 'Support'], function() {
        Route::get('addtiket', ['uses' => 'SupportController@addtiket']);
        Route::post('ajax', ['uses' => 'SupportController@ajax']);
        Route::post('ajaxform', ['uses' => 'SupportController@ajaxform']);

        Route::get('stattiket', ['uses' => 'SupportController@stattiket', 'middleware' => 'ability:admin,']);
        Route::group(['middleware' => 'ability:admin,support-manager'], function() {
            Route::get('listtiket', ['as' => 'support.listtiket', 'uses' => 'SupportController@listtiket']);
            Route::get('viewtiket', ['as' => 'support.viewtiket', 'uses' => 'SupportController@viewtiket']);
            Route::post('addjiro', ['uses' => 'SupportController@addjiro']);
            Route::get('formcomplite', ['uses' => 'SupportController@formcomplite']);
        });

        Route::post('chkauth', ['uses' => 'SupportController@chkauth']);

        Route::get('maintikets', ['uses' => 'SupportController@maintikets']);
        Route::post('maintikets', ['uses' => 'SupportController@maintikets']);
    });

    /*--------------------------------
    Отчет Fullbase
    --------------------------------*/
    Route::group(['middleware' => ['ability:admin,employment-requests']],function() {
        Route::match(['get','post'], '/fullbase', ['uses' => 'FullbaseController@index']);
        Route::get('/edit/create', ['uses' => 'EditController@create']);
        Route::get('/edit/update/{id?}', ['uses' => 'EditController@update']);
        Route::post('/edit/sms_send_addr', ['uses' => 'EditController@ajaxsms']);
        Route::post('/edit/getphones', ['uses' => 'EditController@getphones']);
        Route::post('/edit/formupdate', ['uses' => 'EditController@formupdate']);
        Route::get('/edit/ajax', ['uses' => 'EditController@ajax']);
        Route::post('/edit/ajax', ['uses' => 'EditController@ajax']);
        Route::post('/fullbase/feelds', ['uses' => 'FullbaseController@setFeeldsSoiskateli']);
    });

    /*------------------------
    Банковские карты
    ------------------------*/
    Route::group(['middleware' => ['ability:admin,bank-card']], function() {
        Route::group(['prefix' => 'bankcard',], function () {
            Route::get('', ['as' => 'bankcard.index', 'uses' => 'BankcardController@index']);
            Route::post('ajax', ['uses' => 'BankcardController@ajax']);
            Route::post('', ['uses' => 'BankcardController@index']);
        });
    });
    /*--------------------------------
    Контрагенты
    --------------------------------*/
    Route::group(['prefix' => 'contractor', 'middleware' => ['ability:admin,contractor']], function() {
        Route::match(['get', 'post'],'', ['as' => 'contractor.index', 'uses' => 'ContractorController@index']);
        Route::get('create', ['as' => 'contractor.create', 'uses' => 'ContractorController@create']);
        Route::post('store', ['as' => 'contractor.store', 'uses' => 'ContractorController@store']);
        Route::get('{id}/edit', ['as' => 'contractor.edit', 'uses' => 'ContractorController@edit']);

app/Models/PO/Expense.php
<?php namespace App\Models\PO;

use App\Models\PO\Object;
use Illuminate\Database\Eloquent\Model;

class Expense extends Model
{
    public $table = "po_job_expenses";

    protected $fillable = ['object_id', 'author_id', 'dormitory_cost', 'transport_cost', 'food_cost', 'mk_cost', 'ud_cost', 'other_cost'];
    protected $hidden = ['id', 'object_id', 'author_id', 'created_at', 'updated_at'];

    public function getAttributeNames () {
        return [
            "object_id" => "ID объекта",
            "author_id" => "ID автора",
            "dormitory_cost" => "Проживание",
            "transport_cost" => "Транспорт",
            "food_cost" => "Питание",
            "mk_cost" => "МК (мед. книжка)",
            "ud_cost" => "УД (уд-ние)",
            "other_cost" => "Другие док-ты",
        ];
    }

    public static function getAttributeNamesStatic () {
        return (new Self)->getAttributeNames();
    }

    public function object()
    {
        return $this->belongsTo(Object::class);
    }
}

app/Http/Controllers/PO/ApplicationController.php
<?php namespace App\Http\Controllers\PO;

use App\Http\Requests;
use App\Http\Requests\CreateJobApplicationRequest;
use App\Http\Requests\UpdateJobApplicationRequest;
use App\Libraries\Repositories\JobApplicationRepository;
use Flash;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Validator;
use Response;

class ApplicationController extends Controller
{

	/** @var  JobApplicationRepository */
	private $jobApplicationRepository;

	function __construct(JobApplicationRepository $jobApplicationRepo)
	{
		$this->jobApplicationRepository = $jobApplicationRepo;
		view()->share('object', Route::current()->object);
	}

	/**
	 * Display a listing of the JobApplication.
	 *
	 * @return Response
	 */
	public function index($object)
	{
		return view('po.applications.index')
			->with('jobApplications', $object->applications);
	}

	public function all()
	{
		$jobApplications = $this->jobApplicationRepository->all();
		return view('po.applications.index')
			->with('jobApplications', $jobApplications);
	}

	/**
	 * Show the form for creating a new JobApplication.
	 *
	 * @return Response
	 */
	public function create()
	{
		return view('po.applications.create');
	}

	/**
	 * Store a newly created JobApplication in storage.
	 *
	 * @param CreateJobApplicationRequest $request
	 *
	 * @return Response
	 */
	public function store(CreateJobApplicationRequest $request, $object)
	{
		$params = $request->all();
		$params['author_id'] = \Auth::id();

		$object->applications()->save($this->jobApplicationRepository->create($params));

		return redirect(route('po.applications.index', $object->id));
	}

	/**
	 * Display the specified JobApplication.
	 *
	 * @param  int $id
	 *
	 * @return Response
	 */
	public function show($id)
	{
		$jobApplication = $this->jobApplicationRepository->find($id);

		if(empty($jobApplication))
		{
			Flash::error('Записи не найдены');

			return redirect(route('po.applications.index'));
		}

		return view('jobApplications.show')->with('jobApplication', $jobApplication);
	}

	/**
	 * Show the form for editing the specified JobApplication.
	 *
	 * @param  int $id
	 *
	 * @return Response
	 */
	public function edit($object, $id)
	{
		$jobApplication = $this->jobApplicationRepository->find($id);

		if(empty($jobApplication))
		{
			Flash::error('Запись не найдена');

			return redirect(route('po.applications.index', $object->id));
		}
		return view('po.applications.edit')
			->with('jobApplication', $jobApplication);
	}

	/**
	 * Update the specified JobApplication in storage.
	 *
	 * @param  int              $id
	 * @param UpdateJobApplicationRequest $request
	 *
	 * @return Response
	 */
	public function update($object, $id, UpdateJobApplicationRequest $request)
	{
		$jobApplication = $this->jobApplicationRepository->find($id);

		if(empty($jobApplication))
		{
			Flash::error('Запись не найдена');
			return redirect(route('po.applications.index', $object->id));
		}

		$data = $request->all();
		$data['author_id'] = \Auth::id();

		$this->jobApplicationRepository->updateRich($data, $id);

		Flash::success('Запись успешно обнавлена.');
		return redirect(route('po.applications.index', $object->id));
	}

	/**
	 * Remove the specified JobApplication from storage.
	 *
	 * @param  int $id
	 *
	 * @return Response
	 */
	public function destroy($object, $id)
	{
		$jobApplication = $this->jobApplicationRepository->find($id);
		if(empty($jobApplication))
		{
			Flash::error('Запись не найдена');

			return redirect(route('po.applications.index', $object->id));
		}

		$this->jobApplicationRepository->delete($id);

		Flash::success('Запись удалена.');

		return redirect(route('po.applications.index', $object->id));
	}


}

app/Http/Controllers/PO/ExpenseController.php
<?php namespace App\Http\Controllers\PO;

use App\Http\Requests\UpdatePoExpenseRequest;
use App\Libraries\Repositories\PO\ExpenseRepository;
use App\Models\PO\Expense;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;


class ExpenseController extends Controller
{

	private $expense;
	/** @var  $expenseRepository */
	private $expenseRepository;

	function __construct(Expense $expense, ExpenseRepository $expenseRepo)
	{
		$this->expense = $expense;
		$this->expenseRepository = $expenseRepo;
		view()->share('object', Route::current()->object);
	}

	/**
	 * Display a listing of the Contractor.
	 *
	 * @return Response
	 */
	public function index($object)
	{
		return view('po.expense.index')->withExpense($object->expense);
	}

	public function all()
	{
		return view('po.expense.all')->withExpenses($this->expenseRepository->all());
	}

	public function postindex(UpdatePoExpenseRequest $request, $object)
	{
		$params = array_merge(
			$request->only(['dormitory_cost', 'transport_cost', 'food_cost', 'mk_cost', 'ud_cost', 'other_cost']), ['author_id' => Auth::id()]
		);
		$expense = $object->expense;
		if ($expense) {
			$expense->update($params);
		} else {
			$object->expense()->save($this->expense->fill($params));
		}

		return redirect()->route('po.objects.show', $object->id);
	}
}

app/Http/Controllers/PO/PassportOfficesController.php
<?php namespace App\Http\Controllers\PO;

use App\Http\Requests;
use Flash;
use Mitul\Controller\AppBaseController as AppBaseController;
use Illuminate\Http\Request;
use Response;

class PassportOfficesController extends AppBaseController
{

	/** @var  PassportOfficesRepository */
	private $passportOfficesRepository;

	function __construct()
	{
	}

	public function index(Request $request)
	{

		$passportOffices = \DB::table('po_job_application')->paginate(10);

		return view('po.passportOffices.index')
			->with('passportOffices', $passportOffices);
	}

}

resources/views/po/vacancies/create.blade.php
@section('head')
@stop
@section('scripts')
@stop

@extends('app')

@extends('nav')

@section('content')
<div class="container">

    @include('common.errors')

    {!! Form::open(['route' => 'po.vacancies.store']) !!}

        @include('po.vacancies.fields')

    {!! Form::close() !!}
</div>
@endsection

resources/views/po/vacancies/edit.blade.php
@section('head')
@stop
@section('scripts')
@stop

@extends('app')

@extends('nav')
@section('content')
<div class="container">

    @include('common.errors')

    {!! Form::model($jobVacancy, ['route' => ['po.vacancies.update', $jobVacancy->id], 'method' => 'patch']) !!}

        @include('po.vacancies.fields')

    {!! Form::close() !!}
</div>
@endsection

resources/views/po/vacancies/fields.blade.php
@if( Request()->has('uri') )
    {!! Form::hidden('uri', Request()->get('uri')) !!}
@endif
<div class="col-sm-6 col-lg-4">
    <!-- Name Field -->
    <div class="form-group">
        {!! Form::label('name', 'Вакансия:') !!}
        {!! Form::text('name', null, ['class' => 'form-control']) !!}
    </div>

    @if (!isset($jobVacancy) or !$jobVacancy->childrens->count() )
        <div class="form-group">
            {!! Form::label('parent_id', 'Родительская категория:') !!}
            {!! Form::select('parent_id', $parents, null, ['class' => 'form-control', 'placeholder'=>'Родительская категория']) !!}
        </div>
    @endif
</div>

<div style="clear: both;"></div>


<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Сохранить', ['class' => 'btn btn-primary']) !!}
    @if( Request()->has('uri') )
        {!! Html::link(Request()->get('uri'), 'Отмена', ['class' => 'btn btn-default']) !!}
    @endif
    {!! Html::linkRoute('po.vacancies.index', 'Перейти к списку вакансий', [], ['class' => 'btn btn-default']) !!}
</div>

resources/views/po/vacancies/index.blade.php
@section('head')
@stop
@section('scripts')
@stop


@extends('app')

@extends('nav')

@section('content')

    <div class="container">

        @include('flash::message')

        <div class="row">
            <h1 class="pull-left">Список вакансий</h1>
            <a class="btn btn-primary pull-right" style="margin-top: 25px" href="{!! route('po.vacancies.create') !!}">Добавить вакансию</a>
        </div>

        <div class="row">
            @if($jobVacancies->isEmpty())
                <div class="well text-center">Вакансии не найдены.</div>
            @else
                @include('po.vacancies.table')
            @endif
        </div>


    </div>
@endsection

resources/views/po/vacancies/show.blade.php
@extends('app')

@section('content')
<div class="container">
	 @include('po.vacancies.show_fields')
</div>
@endsection

resources/views/po/vacancies/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $jobVacancy->id !!}</p>
</div>

<!-- Name Field -->
<div class="form-group">
    {!! Form::label('name', 'Name:') !!}
    <p>{!! $jobVacancy->name !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{!! $jobVacancy->updated_at !!}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{!! $jobVacancy->created_at !!}</p>
</div>

resources/views/po/vacancies/table.blade.php
<table class="table">
    <thead>
            <th>№</th>
			<th>Вакансия</th>
			<th>Дата создания</th>
    <th width="50px">Действия</th>
    </thead>
    <tbody>
    @foreach($jobVacancies as $jobVacancy)
        <tr>
            <td>{{ $jobVacancy->id }}</td>
			<td><b>{{ $jobVacancy->name }}</b></td>
			<td>{{ $jobVacancy->created_at }}</td>
            <td>
                <a href="{!! route('po.vacancies.edit', [$jobVacancy->id]) !!}"><i class="glyphicon glyphicon-edit"></i></a>
                <a href="{!! route('po.vacancies.delete', [$jobVacancy->id]) !!}" onclick="return confirm('Are you sure wants to delete this JobVacancy?')"><i class="glyphicon glyphicon-remove"></i></a>
            </td>
        </tr>
        @foreach($jobVacancy->childrens as $children)
            <tr>
                <td>{{ $children->id }}</td>
                <td><i>&#8212; {{ $children->name }}</i></td>
                <td>{{ $children->created_at }}</td>
                <td>
                    <a href="{!! route('po.vacancies.edit', [$children->id]) !!}"><i class="glyphicon glyphicon-edit"></i></a>
                    <a href="{!! route('po.vacancies.delete', [$children->id]) !!}" onclick="return confirm('Are you sure wants to delete this JobVacancy?')"><i class="glyphicon glyphicon-remove"></i></a>
                </td>
            </tr>
        @endforeach
    @endforeach
    </tbody>
</table>